version: '3.7'

services:
  integration:
    image: jupiter-integration-tenable-app
    build: .
    container_name: jupiter-integration-tenable-app
    volumes:
      - .:/app:cached
      - ~/.ssh:/root/.ssh
      - ~/.bash_history:/root/.bash_history
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      GRAPH_DB_ENDPOINT: graph
      TENABLE_LOCAL_EXECUTION_ACCESS_KEY: 'YOUR TENABLE ACCESS KEY HERE'
      TENABLE_LOCAL_EXECUTION_SECRET_KEY: 'YOUR TENABLE SECRET KEY HERE'
    depends_on:
      - graph
  graph:
    image: tinkerpop/gremlin-server:3.3
    restart: unless-stopped
    ports:
      - "8182:8182"
